// Embeds schema/*.schema.json into packages/format/src/schemas.gen.ts so the format package can
// validate in Node and the browser without file access. Run: `pnpm gen:schemas`.
// A test (packages/format/test/schemas.test.ts) fails when the generated file is stale.
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
export const SCHEMA_NAMES = ['manifest', 'ids', 'shot', 'assets', 'timeline'];

export function renderSchemasModule() {
  const parts = SCHEMA_NAMES.map((name) => {
    const json = JSON.parse(readFileSync(join(root, 'schema', `${name}.schema.json`), 'utf8'));
    return `  ${name}: ${JSON.stringify(json)},`;
  });
  return [
    '// GENERATED by scripts/gen-schemas.mjs from schema/*.schema.json. Do not edit.',
    '/* eslint-disable */',
    'export const SCHEMAS = {',
    ...parts,
    '} as const;',
    '',
    'export type SchemaName = keyof typeof SCHEMAS;',
    '',
  ].join('\n');
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const out = join(root, 'packages/format/src/schemas.gen.ts');
  writeFileSync(out, renderSchemasModule());
  console.log(`wrote ${out}`);
}
